database:
    connection_string: 'mssql+pyodbc://LAPTOP-H1G95B7K\\2022@LAPTOP-H1G95B7K\\SQLEXPRESS/LuxuryRest?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes'
tables:
  - name: User
    columns: ['id', 'name', 'email', 'password', 'active', 'confirmed_at']
  - name: Role
    columns: ['id', 'name', 'email', 'password', 'active', 'confirmed_at']
